name: proper_life
description: "A new Flutter project."

publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.1.0
  firebase_core: ^2.25.4
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.5
  fluttertoast: ^8.2.4
  flutter_bloc: ^8.1.4
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^9.1.0
  dropdown_search: ^5.0.6
  image_picker: ^1.0.7
  firebase_storage: ^11.6.9
  flutter_linkify: ^6.0.0
  url_launcher: ^6.2.5
  intl: ^0.18.1
  font_awesome_flutter: ^10.7.0
  flutter_markdown: ^0.7.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/privacy_policy/

flutter_intl:
  enabled: true
